language: go
go: 1.x

before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then 
      echo "on master";
      openssl aes-256-cbc -K $encrypted_d626980ed8c7_key -iv $encrypted_d626980ed8c7_iv -in Cooling\ Monitoring-1375152f4583.json.enc -out appengine.json -d;
      sed -i 's/$TOKEN/'$SIGFOX_TOKEN'/g' app.yaml;
    fi

deploy:
  provider: gae
  keyfile: "appengine.json"
  project: "cooling-monitoring"
  on: master
  skip_cleanup: true