runtime: go
api_version: go1.8

handlers:
  - url: /.*
    script: _go_app
    secure: always

env_variables:
  SIGFOX_API_TOKEN: '$TOKEN'

cron:
- description: keep backend alive
  url: /
  schedule: every 5 mins